In [1]:
!pip install pandas

Requirement already satisfied: pandas in ./venv/lib/python3.10/site-packages (2.1.2)
Requirement already satisfied: numpy<2,>=1.22.4 in ./venv/lib/python3.10/site-packages (from pandas) (1.26.1)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.10/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in ./venv/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the '/Users/krzysztofpraca/Projects/hackathon-2023/venv/bin/python3 -m pip install --upgrade pip' command.

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('worldcities.csv')

In [7]:
df[df['iso2'] == 'PL']

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
440,Warsaw,Warsaw,52.2300,21.0111,Poland,PL,POL,Mazowieckie,primary,1860281.0,1616024847
1071,Kraków,Krakow,50.0614,19.9372,Poland,PL,POL,Małopolskie,admin,800653.0,1616172264
1207,Łódź,Lodz,51.7769,19.4547,Poland,PL,POL,Łódzkie,admin,690422.0,1616832750
1226,Wrocław,Wroclaw,51.1100,17.0325,Poland,PL,POL,Dolnośląskie,admin,672929.0,1616108520
1440,Poznań,Poznan,52.4083,16.9336,Poland,PL,POL,Wielkopolskie,admin,546859.0,1616725607
...,...,...,...,...,...,...,...,...,...,...,...
43290,Strzyżów,Strzyzow,49.8833,21.7833,Poland,PL,POL,Podkarpackie,minor,8588.0,1616515144
43310,Kościelisko,Koscielisko,49.2833,19.8833,Poland,PL,POL,Małopolskie,NaN,8661.0,1616942761
43344,Żuromin,Zuromin,53.0667,19.9000,Poland,PL,POL,Mazowieckie,minor,8592.0,1616921543
43367,Poniatowa,Poniatowa,51.1833,22.0667,Poland,PL,POL,Lubelskie,NaN,8517.0,1616798001
43408,Wieruszów,Wieruszow,51.3000,18.1500,Poland,PL,POL,Łódzkie,minor,8514.0,1616576051

In [ ]:
class City:
    def __init__(self, name, lat, lng):
        self.name = name
        self.lat = lat
        self.lng = lng

    def get_spatial_extent(self, radius=0.2):
        spatial_extent = {
            "west": self.long-radius, 
            "south": self.lat-radius, 
            "east": self.long+radius, 
            "north": self.lat+radius
        }
        return spatial_extent

    def get_features(self, radius=0.15):
        features = {
            "type": "FeatureCollection", 
            "features": [
                {
                    "type": "Feature", 
                    "properties": {},
                    "geometry": {
                        "type": "Polygon", 
                        "coordinates": [
                            [
                                [self.lat - radius, self.long - radius], 
                                [self.lat + radius, self.long - radius], 
                                [self.lat + radius, self.long + radius], 
                                [self.lat - radius, self.long + radius], 
                                [self.lat - radius, self.long - radius]
                            ]
                        ]
                    }
                }
            ]
        }
        return features